env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:vue/vue3-essential
  - "@unocss"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {}
